fragment SiteConfigParts on SiteConfig {
  __typename
  siteName
  tagline
  logoUrl
  accentColor
  social {
    __typename
    twitter
    linkedin
    github
  }
}

fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    eyebrowText
    headline
    subheadline
    primaryCta {
      __typename
      label
      href
    }
    secondaryCta {
      __typename
      label
      href
    }
  }
  stats {
    __typename
    value
    label
  }
  scrollStory {
    __typename
    num
    heading
    body
    tag
    url
  }
  features {
    __typename
    icon
    title
    body
  }
  outro {
    __typename
    headline
    subheadline
    ctaPrimary {
      __typename
      label
      href
    }
    ctaSecondary {
      __typename
      label
      href
    }
  }
}

fragment DemosParts on Demos {
  __typename
  name
  slug
  industry
  description
  kpis
  tags
  featured
  href
}

fragment NavigationParts on Navigation {
  __typename
  links {
    __typename
    label
    href
  }
  ctaLabel
  ctaHref
}

fragment FooterParts on Footer {
  __typename
  tagline
  copyright
  linkGroups {
    __typename
    title
    links {
      __typename
      label
      href
    }
  }
  socialLinks {
    __typename
    label
    href
  }
}

fragment PagesParts on Pages {
  __typename
  title
  slug
  content
}
