//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteConfig: SiteConfig;
  siteConfigConnection: SiteConfigConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  demos: Demos;
  demosConnection: DemosConnection;
  navigation: Navigation;
  navigationConnection: NavigationConnection;
  footer: Footer;
  footerConnection: FooterConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConfigArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConfigConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteConfigFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryDemosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDemosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DemosFilter>;
};


export type QueryNavigationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavigationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavigationFilter>;
};


export type QueryFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};

export type DocumentFilter = {
  siteConfig?: InputMaybe<SiteConfigFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  demos?: InputMaybe<DemosFilter>;
  navigation?: InputMaybe<NavigationFilter>;
  footer?: InputMaybe<FooterFilter>;
  pages?: InputMaybe<PagesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteConfig | Homepage | Demos | Navigation | Footer | Pages | Folder;

export type SiteConfigSocial = {
  __typename?: 'SiteConfigSocial';
  twitter?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  github?: Maybe<Scalars['String']['output']>;
};

export type SiteConfig = Node & Document & {
  __typename?: 'SiteConfig';
  siteName?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  logoUrl?: Maybe<Scalars['String']['output']>;
  accentColor?: Maybe<Scalars['String']['output']>;
  social?: Maybe<SiteConfigSocial>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteConfigSocialFilter = {
  twitter?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  github?: InputMaybe<StringFilter>;
};

export type SiteConfigFilter = {
  siteName?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  logoUrl?: InputMaybe<ImageFilter>;
  accentColor?: InputMaybe<StringFilter>;
  social?: InputMaybe<SiteConfigSocialFilter>;
};

export type SiteConfigConnectionEdges = {
  __typename?: 'SiteConfigConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteConfig>;
};

export type SiteConfigConnection = Connection & {
  __typename?: 'SiteConfigConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConfigConnectionEdges>>>;
};

export type HomepageHeroPrimaryCta = {
  __typename?: 'HomepageHeroPrimaryCta';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type HomepageHeroSecondaryCta = {
  __typename?: 'HomepageHeroSecondaryCta';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type HomepageHero = {
  __typename?: 'HomepageHero';
  eyebrowText?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  subheadline?: Maybe<Scalars['String']['output']>;
  primaryCta?: Maybe<HomepageHeroPrimaryCta>;
  secondaryCta?: Maybe<HomepageHeroSecondaryCta>;
};

export type HomepageStats = {
  __typename?: 'HomepageStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type HomepageScrollStory = {
  __typename?: 'HomepageScrollStory';
  num?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  tag?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type HomepageFeatures = {
  __typename?: 'HomepageFeatures';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomepageOutroCtaPrimary = {
  __typename?: 'HomepageOutroCtaPrimary';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type HomepageOutroCtaSecondary = {
  __typename?: 'HomepageOutroCtaSecondary';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type HomepageOutro = {
  __typename?: 'HomepageOutro';
  headline?: Maybe<Scalars['String']['output']>;
  subheadline?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<HomepageOutroCtaPrimary>;
  ctaSecondary?: Maybe<HomepageOutroCtaSecondary>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  hero?: Maybe<HomepageHero>;
  stats?: Maybe<Array<Maybe<HomepageStats>>>;
  scrollStory?: Maybe<Array<Maybe<HomepageScrollStory>>>;
  features?: Maybe<Array<Maybe<HomepageFeatures>>>;
  outro?: Maybe<HomepageOutro>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageHeroPrimaryCtaFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageHeroSecondaryCtaFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageHeroFilter = {
  eyebrowText?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  subheadline?: InputMaybe<StringFilter>;
  primaryCta?: InputMaybe<HomepageHeroPrimaryCtaFilter>;
  secondaryCta?: InputMaybe<HomepageHeroSecondaryCtaFilter>;
};

export type HomepageStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HomepageScrollStoryFilter = {
  num?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  tag?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type HomepageFeaturesFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomepageOutroCtaPrimaryFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageOutroCtaSecondaryFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type HomepageOutroFilter = {
  headline?: InputMaybe<StringFilter>;
  subheadline?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<HomepageOutroCtaPrimaryFilter>;
  ctaSecondary?: InputMaybe<HomepageOutroCtaSecondaryFilter>;
};

export type HomepageFilter = {
  hero?: InputMaybe<HomepageHeroFilter>;
  stats?: InputMaybe<HomepageStatsFilter>;
  scrollStory?: InputMaybe<HomepageScrollStoryFilter>;
  features?: InputMaybe<HomepageFeaturesFilter>;
  outro?: InputMaybe<HomepageOutroFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Demos = Node & Document & {
  __typename?: 'Demos';
  name: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  industry?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  kpis?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DemosFilter = {
  name?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  industry?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  kpis?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  href?: InputMaybe<StringFilter>;
};

export type DemosConnectionEdges = {
  __typename?: 'DemosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Demos>;
};

export type DemosConnection = Connection & {
  __typename?: 'DemosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DemosConnectionEdges>>>;
};

export type NavigationLinks = {
  __typename?: 'NavigationLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type Navigation = Node & Document & {
  __typename?: 'Navigation';
  links?: Maybe<Array<Maybe<NavigationLinks>>>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaHref?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavigationLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type NavigationFilter = {
  links?: InputMaybe<NavigationLinksFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaHref?: InputMaybe<StringFilter>;
};

export type NavigationConnectionEdges = {
  __typename?: 'NavigationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Navigation>;
};

export type NavigationConnection = Connection & {
  __typename?: 'NavigationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavigationConnectionEdges>>>;
};

export type FooterLinkGroupsLinks = {
  __typename?: 'FooterLinkGroupsLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type FooterLinkGroups = {
  __typename?: 'FooterLinkGroups';
  title?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<FooterLinkGroupsLinks>>>;
};

export type FooterSocialLinks = {
  __typename?: 'FooterSocialLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type Footer = Node & Document & {
  __typename?: 'Footer';
  tagline?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  linkGroups?: Maybe<Array<Maybe<FooterLinkGroups>>>;
  socialLinks?: Maybe<Array<Maybe<FooterSocialLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FooterLinkGroupsLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type FooterLinkGroupsFilter = {
  title?: InputMaybe<StringFilter>;
  links?: InputMaybe<FooterLinkGroupsLinksFilter>;
};

export type FooterSocialLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type FooterFilter = {
  tagline?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  linkGroups?: InputMaybe<FooterLinkGroupsFilter>;
  socialLinks?: InputMaybe<FooterSocialLinksFilter>;
};

export type FooterConnectionEdges = {
  __typename?: 'FooterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Footer>;
};

export type FooterConnection = Connection & {
  __typename?: 'FooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FooterConnectionEdges>>>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title: Scalars['String']['output'];
  slug?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteConfig: SiteConfig;
  createSiteConfig: SiteConfig;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateDemos: Demos;
  createDemos: Demos;
  updateNavigation: Navigation;
  createNavigation: Navigation;
  updateFooter: Footer;
  createFooter: Footer;
  updatePages: Pages;
  createPages: Pages;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteConfigMutation;
};


export type MutationCreateSiteConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteConfigMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateDemosArgs = {
  relativePath: Scalars['String']['input'];
  params: DemosMutation;
};


export type MutationCreateDemosArgs = {
  relativePath: Scalars['String']['input'];
  params: DemosMutation;
};


export type MutationUpdateNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: NavigationMutation;
};


export type MutationCreateNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: NavigationMutation;
};


export type MutationUpdateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationCreateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};

export type DocumentUpdateMutation = {
  siteConfig?: InputMaybe<SiteConfigMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  demos?: InputMaybe<DemosMutation>;
  navigation?: InputMaybe<NavigationMutation>;
  footer?: InputMaybe<FooterMutation>;
  pages?: InputMaybe<PagesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteConfig?: InputMaybe<SiteConfigMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  demos?: InputMaybe<DemosMutation>;
  navigation?: InputMaybe<NavigationMutation>;
  footer?: InputMaybe<FooterMutation>;
  pages?: InputMaybe<PagesMutation>;
};

export type SiteConfigSocialMutation = {
  twitter?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  github?: InputMaybe<Scalars['String']['input']>;
};

export type SiteConfigMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  logoUrl?: InputMaybe<Scalars['String']['input']>;
  accentColor?: InputMaybe<Scalars['String']['input']>;
  social?: InputMaybe<SiteConfigSocialMutation>;
};

export type HomepageHeroPrimaryCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroSecondaryCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageHeroMutation = {
  eyebrowText?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  subheadline?: InputMaybe<Scalars['String']['input']>;
  primaryCta?: InputMaybe<HomepageHeroPrimaryCtaMutation>;
  secondaryCta?: InputMaybe<HomepageHeroSecondaryCtaMutation>;
};

export type HomepageStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageScrollStoryMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageFeaturesMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageOutroCtaPrimaryMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageOutroCtaSecondaryMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageOutroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subheadline?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<HomepageOutroCtaPrimaryMutation>;
  ctaSecondary?: InputMaybe<HomepageOutroCtaSecondaryMutation>;
};

export type HomepageMutation = {
  hero?: InputMaybe<HomepageHeroMutation>;
  stats?: InputMaybe<Array<InputMaybe<HomepageStatsMutation>>>;
  scrollStory?: InputMaybe<Array<InputMaybe<HomepageScrollStoryMutation>>>;
  features?: InputMaybe<Array<InputMaybe<HomepageFeaturesMutation>>>;
  outro?: InputMaybe<HomepageOutroMutation>;
};

export type DemosMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  industry?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  kpis?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type NavigationLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type NavigationMutation = {
  links?: InputMaybe<Array<InputMaybe<NavigationLinksMutation>>>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaHref?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLinkGroupsLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLinkGroupsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<FooterLinkGroupsLinksMutation>>>;
};

export type FooterSocialLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type FooterMutation = {
  tagline?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  linkGroups?: InputMaybe<Array<InputMaybe<FooterLinkGroupsMutation>>>;
  socialLinks?: InputMaybe<Array<InputMaybe<FooterSocialLinksMutation>>>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['JSON']['input']>;
};

export type SiteConfigPartsFragment = { __typename: 'SiteConfig', siteName?: string | null, tagline?: string | null, logoUrl?: string | null, accentColor?: string | null, social?: { __typename: 'SiteConfigSocial', twitter?: string | null, linkedin?: string | null, github?: string | null } | null };

export type HomepagePartsFragment = { __typename: 'Homepage', hero?: { __typename: 'HomepageHero', eyebrowText?: string | null, headline?: string | null, subheadline?: string | null, primaryCta?: { __typename: 'HomepageHeroPrimaryCta', label?: string | null, href?: string | null } | null, secondaryCta?: { __typename: 'HomepageHeroSecondaryCta', label?: string | null, href?: string | null } | null } | null, stats?: Array<{ __typename: 'HomepageStats', value?: string | null, label?: string | null } | null> | null, scrollStory?: Array<{ __typename: 'HomepageScrollStory', num?: string | null, heading?: string | null, body?: string | null, tag?: string | null, url?: string | null } | null> | null, features?: Array<{ __typename: 'HomepageFeatures', icon?: string | null, title?: string | null, body?: string | null } | null> | null, outro?: { __typename: 'HomepageOutro', headline?: string | null, subheadline?: string | null, ctaPrimary?: { __typename: 'HomepageOutroCtaPrimary', label?: string | null, href?: string | null } | null, ctaSecondary?: { __typename: 'HomepageOutroCtaSecondary', label?: string | null, href?: string | null } | null } | null };

export type DemosPartsFragment = { __typename: 'Demos', name: string, slug?: string | null, industry?: string | null, description?: string | null, kpis?: Array<string | null> | null, tags?: Array<string | null> | null, featured?: boolean | null, href?: string | null };

export type NavigationPartsFragment = { __typename: 'Navigation', ctaLabel?: string | null, ctaHref?: string | null, links?: Array<{ __typename: 'NavigationLinks', label?: string | null, href?: string | null } | null> | null };

export type FooterPartsFragment = { __typename: 'Footer', tagline?: string | null, copyright?: string | null, linkGroups?: Array<{ __typename: 'FooterLinkGroups', title?: string | null, links?: Array<{ __typename: 'FooterLinkGroupsLinks', label?: string | null, href?: string | null } | null> | null } | null> | null, socialLinks?: Array<{ __typename: 'FooterSocialLinks', label?: string | null, href?: string | null } | null> | null };

export type PagesPartsFragment = { __typename: 'Pages', title: string, slug?: string | null, content?: any | null };

export type SiteConfigQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteConfigQuery = { __typename?: 'Query', siteConfig: { __typename: 'SiteConfig', id: string, siteName?: string | null, tagline?: string | null, logoUrl?: string | null, accentColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteConfigSocial', twitter?: string | null, linkedin?: string | null, github?: string | null } | null } };

export type SiteConfigConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteConfigFilter>;
}>;


export type SiteConfigConnectionQuery = { __typename?: 'Query', siteConfigConnection: { __typename?: 'SiteConfigConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConfigConnectionEdges', cursor: string, node?: { __typename: 'SiteConfig', id: string, siteName?: string | null, tagline?: string | null, logoUrl?: string | null, accentColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, social?: { __typename: 'SiteConfigSocial', twitter?: string | null, linkedin?: string | null, github?: string | null } | null } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomepageHero', eyebrowText?: string | null, headline?: string | null, subheadline?: string | null, primaryCta?: { __typename: 'HomepageHeroPrimaryCta', label?: string | null, href?: string | null } | null, secondaryCta?: { __typename: 'HomepageHeroSecondaryCta', label?: string | null, href?: string | null } | null } | null, stats?: Array<{ __typename: 'HomepageStats', value?: string | null, label?: string | null } | null> | null, scrollStory?: Array<{ __typename: 'HomepageScrollStory', num?: string | null, heading?: string | null, body?: string | null, tag?: string | null, url?: string | null } | null> | null, features?: Array<{ __typename: 'HomepageFeatures', icon?: string | null, title?: string | null, body?: string | null } | null> | null, outro?: { __typename: 'HomepageOutro', headline?: string | null, subheadline?: string | null, ctaPrimary?: { __typename: 'HomepageOutroCtaPrimary', label?: string | null, href?: string | null } | null, ctaSecondary?: { __typename: 'HomepageOutroCtaSecondary', label?: string | null, href?: string | null } | null } | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomepageHero', eyebrowText?: string | null, headline?: string | null, subheadline?: string | null, primaryCta?: { __typename: 'HomepageHeroPrimaryCta', label?: string | null, href?: string | null } | null, secondaryCta?: { __typename: 'HomepageHeroSecondaryCta', label?: string | null, href?: string | null } | null } | null, stats?: Array<{ __typename: 'HomepageStats', value?: string | null, label?: string | null } | null> | null, scrollStory?: Array<{ __typename: 'HomepageScrollStory', num?: string | null, heading?: string | null, body?: string | null, tag?: string | null, url?: string | null } | null> | null, features?: Array<{ __typename: 'HomepageFeatures', icon?: string | null, title?: string | null, body?: string | null } | null> | null, outro?: { __typename: 'HomepageOutro', headline?: string | null, subheadline?: string | null, ctaPrimary?: { __typename: 'HomepageOutroCtaPrimary', label?: string | null, href?: string | null } | null, ctaSecondary?: { __typename: 'HomepageOutroCtaSecondary', label?: string | null, href?: string | null } | null } | null } | null } | null> | null } };

export type DemosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DemosQuery = { __typename?: 'Query', demos: { __typename: 'Demos', id: string, name: string, slug?: string | null, industry?: string | null, description?: string | null, kpis?: Array<string | null> | null, tags?: Array<string | null> | null, featured?: boolean | null, href?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DemosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DemosFilter>;
}>;


export type DemosConnectionQuery = { __typename?: 'Query', demosConnection: { __typename?: 'DemosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DemosConnectionEdges', cursor: string, node?: { __typename: 'Demos', id: string, name: string, slug?: string | null, industry?: string | null, description?: string | null, kpis?: Array<string | null> | null, tags?: Array<string | null> | null, featured?: boolean | null, href?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NavigationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavigationQuery = { __typename?: 'Query', navigation: { __typename: 'Navigation', id: string, ctaLabel?: string | null, ctaHref?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavigationLinks', label?: string | null, href?: string | null } | null> | null } };

export type NavigationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavigationFilter>;
}>;


export type NavigationConnectionQuery = { __typename?: 'Query', navigationConnection: { __typename?: 'NavigationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavigationConnectionEdges', cursor: string, node?: { __typename: 'Navigation', id: string, ctaLabel?: string | null, ctaHref?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavigationLinks', label?: string | null, href?: string | null } | null> | null } | null } | null> | null } };

export type FooterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FooterQuery = { __typename?: 'Query', footer: { __typename: 'Footer', id: string, tagline?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, linkGroups?: Array<{ __typename: 'FooterLinkGroups', title?: string | null, links?: Array<{ __typename: 'FooterLinkGroupsLinks', label?: string | null, href?: string | null } | null> | null } | null> | null, socialLinks?: Array<{ __typename: 'FooterSocialLinks', label?: string | null, href?: string | null } | null> | null } };

export type FooterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
}>;


export type FooterConnectionQuery = { __typename?: 'Query', footerConnection: { __typename?: 'FooterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FooterConnectionEdges', cursor: string, node?: { __typename: 'Footer', id: string, tagline?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, linkGroups?: Array<{ __typename: 'FooterLinkGroups', title?: string | null, links?: Array<{ __typename: 'FooterLinkGroupsLinks', label?: string | null, href?: string | null } | null> | null } | null> | null, socialLinks?: Array<{ __typename: 'FooterSocialLinks', label?: string | null, href?: string | null } | null> | null } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, title: string, slug?: string | null, content?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, title: string, slug?: string | null, content?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SiteConfigPartsFragmentDoc = gql`
    fragment SiteConfigParts on SiteConfig {
  __typename
  siteName
  tagline
  logoUrl
  accentColor
  social {
    __typename
    twitter
    linkedin
    github
  }
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    eyebrowText
    headline
    subheadline
    primaryCta {
      __typename
      label
      href
    }
    secondaryCta {
      __typename
      label
      href
    }
  }
  stats {
    __typename
    value
    label
  }
  scrollStory {
    __typename
    num
    heading
    body
    tag
    url
  }
  features {
    __typename
    icon
    title
    body
  }
  outro {
    __typename
    headline
    subheadline
    ctaPrimary {
      __typename
      label
      href
    }
    ctaSecondary {
      __typename
      label
      href
    }
  }
}
    `;
export const DemosPartsFragmentDoc = gql`
    fragment DemosParts on Demos {
  __typename
  name
  slug
  industry
  description
  kpis
  tags
  featured
  href
}
    `;
export const NavigationPartsFragmentDoc = gql`
    fragment NavigationParts on Navigation {
  __typename
  links {
    __typename
    label
    href
  }
  ctaLabel
  ctaHref
}
    `;
export const FooterPartsFragmentDoc = gql`
    fragment FooterParts on Footer {
  __typename
  tagline
  copyright
  linkGroups {
    __typename
    title
    links {
      __typename
      label
      href
    }
  }
  socialLinks {
    __typename
    label
    href
  }
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  slug
  content
}
    `;
export const SiteConfigDocument = gql`
    query siteConfig($relativePath: String!) {
  siteConfig(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteConfigParts
  }
}
    ${SiteConfigPartsFragmentDoc}`;
export const SiteConfigConnectionDocument = gql`
    query siteConfigConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteConfigFilter) {
  siteConfigConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteConfigParts
      }
    }
  }
}
    ${SiteConfigPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const DemosDocument = gql`
    query demos($relativePath: String!) {
  demos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DemosParts
  }
}
    ${DemosPartsFragmentDoc}`;
export const DemosConnectionDocument = gql`
    query demosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DemosFilter) {
  demosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DemosParts
      }
    }
  }
}
    ${DemosPartsFragmentDoc}`;
export const NavigationDocument = gql`
    query navigation($relativePath: String!) {
  navigation(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavigationParts
  }
}
    ${NavigationPartsFragmentDoc}`;
export const NavigationConnectionDocument = gql`
    query navigationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavigationFilter) {
  navigationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavigationParts
      }
    }
  }
}
    ${NavigationPartsFragmentDoc}`;
export const FooterDocument = gql`
    query footer($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FooterParts
  }
}
    ${FooterPartsFragmentDoc}`;
export const FooterConnectionDocument = gql`
    query footerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FooterFilter) {
  footerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FooterParts
      }
    }
  }
}
    ${FooterPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteConfig(variables: SiteConfigQueryVariables, options?: C): Promise<{data: SiteConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigQueryVariables, query: string}> {
        return requester<{data: SiteConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigQueryVariables, query: string}, SiteConfigQueryVariables>(SiteConfigDocument, variables, options);
      },
    siteConfigConnection(variables?: SiteConfigConnectionQueryVariables, options?: C): Promise<{data: SiteConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConfigConnectionQueryVariables, query: string}, SiteConfigConnectionQueryVariables>(SiteConfigConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    demos(variables: DemosQueryVariables, options?: C): Promise<{data: DemosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DemosQueryVariables, query: string}> {
        return requester<{data: DemosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DemosQueryVariables, query: string}, DemosQueryVariables>(DemosDocument, variables, options);
      },
    demosConnection(variables?: DemosConnectionQueryVariables, options?: C): Promise<{data: DemosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DemosConnectionQueryVariables, query: string}> {
        return requester<{data: DemosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DemosConnectionQueryVariables, query: string}, DemosConnectionQueryVariables>(DemosConnectionDocument, variables, options);
      },
    navigation(variables: NavigationQueryVariables, options?: C): Promise<{data: NavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationQueryVariables, query: string}> {
        return requester<{data: NavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationQueryVariables, query: string}, NavigationQueryVariables>(NavigationDocument, variables, options);
      },
    navigationConnection(variables?: NavigationConnectionQueryVariables, options?: C): Promise<{data: NavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationConnectionQueryVariables, query: string}> {
        return requester<{data: NavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationConnectionQueryVariables, query: string}, NavigationConnectionQueryVariables>(NavigationConnectionDocument, variables, options);
      },
    footer(variables: FooterQueryVariables, options?: C): Promise<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}> {
        return requester<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}, FooterQueryVariables>(FooterDocument, variables, options);
      },
    footerConnection(variables?: FooterConnectionQueryVariables, options?: C): Promise<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}> {
        return requester<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}, FooterConnectionQueryVariables>(FooterConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  