-- =========================================================================
-- FALCON HR ANALYTICS - QUERY TEMPLATES
-- =========================================================================
-- Starter SQL queries for all 9 dashboards
-- Each query uses actual column names and is ready to paste into ida_query()
-- Customize filters and date ranges as needed for your dashboard
-- =========================================================================

-- =========================================================================
-- DASHBOARD 1: WORKFORCE OVERVIEW
-- =========================================================================

-- 1.1: Total Headcount (Current, by Status)
SELECT
  COUNT(DISTINCT EMPLOYEE_ID) AS TOTAL_HEADCOUNT,
  COUNT(DISTINCT CASE WHEN EMPLOYEE_STATUS = 'Active' THEN EMPLOYEE_ID END) AS ACTIVE,
  COUNT(DISTINCT CASE WHEN EMPLOYEE_STATUS = 'On Leave' THEN EMPLOYEE_ID END) AS ON_LEAVE,
  COUNT(DISTINCT CASE WHEN EMPLOYEE_STATUS = 'Terminated' THEN EMPLOYEE_ID END) AS TERMINATED
FROM EMPLOYEES
WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave');

-- 1.2: Headcount by Department
SELECT
  D.DEPARTMENT_NAME,
  D.DEPARTMENT_CODE,
  COUNT(DISTINCT E.EMPLOYEE_ID) AS HEADCOUNT
FROM EMPLOYEES E
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON E.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
  AND D.IS_ACTIVE = TRUE
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, D.DEPARTMENT_CODE
ORDER BY HEADCOUNT DESC;

-- 1.3: Turnover Rate (Annual, All Types)
SELECT
  ROUND(
    (COUNT(DISTINCT E.EMPLOYEE_ID) / AVG_HC) * 100,
    2
  ) AS TURNOVER_RATE_PCT
FROM (
  SELECT COUNT(DISTINCT EMPLOYEE_ID) AS CNT
  FROM EXIT_RECORDS
  WHERE TERMINATION_DATE >= DATE_TRUNC('year', CURRENT_DATE)
) E
CROSS JOIN (
  SELECT AVG(HC) AS AVG_HC FROM (
    SELECT
      DATE_TRUNC('month', EFFECTIVE_DATE) AS MONTH,
      COUNT(DISTINCT EMPLOYEE_ID) AS HC
    FROM EMPLOYEE_ASSIGNMENTS
    WHERE END_DATE IS NULL
    GROUP BY DATE_TRUNC('month', EFFECTIVE_DATE)
  ) MONTHLY_HC
) HC;

-- 1.4: New Hires YTD
SELECT
  COUNT(DISTINCT EMPLOYEE_ID) AS NEW_HIRES_YTD,
  ROUND(AVG(YEAR(HIRE_DATE)), 0) AS AVG_HIRE_YEAR
FROM EMPLOYEES
WHERE YEAR(HIRE_DATE) = YEAR(CURRENT_DATE)
  AND EMPLOYEE_STATUS IN ('Active', 'On Leave');

-- =========================================================================
-- DASHBOARD 2: DEPARTMENT ANALYTICS
-- =========================================================================

-- 2.1: Headcount by Department with Cost Center
SELECT
  D.DEPARTMENT_NAME,
  CC.COST_CENTER_CODE,
  CC.COST_CENTER_NAME,
  COUNT(DISTINCT E.EMPLOYEE_ID) AS HEADCOUNT,
  COUNT(DISTINCT CASE WHEN E.EMPLOYMENT_TYPE = 'Full-time' THEN E.EMPLOYEE_ID END) AS FTE_FULL_TIME,
  COUNT(DISTINCT CASE WHEN E.EMPLOYMENT_TYPE = 'Part-time' THEN E.EMPLOYEE_ID END) AS FTE_PART_TIME,
  COUNT(DISTINCT CASE WHEN E.EMPLOYMENT_TYPE = 'Contract' THEN E.EMPLOYEE_ID END) AS FTE_CONTRACT
FROM EMPLOYEES E
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON E.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN COST_CENTERS CC
  ON D.COST_CENTER_ID = CC.COST_CENTER_ID
WHERE E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
  AND D.IS_ACTIVE = TRUE
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME, CC.COST_CENTER_ID, CC.COST_CENTER_CODE, CC.COST_CENTER_NAME
ORDER BY HEADCOUNT DESC;

-- 2.2: Department Turnover Rate (Last 12 Months)
SELECT
  D.DEPARTMENT_NAME,
  COUNT(DISTINCT ER.EMPLOYEE_ID) AS SEPARATIONS,
  ROUND(
    (COUNT(DISTINCT ER.EMPLOYEE_ID) / NULLIF(AVG_HC, 0)) * 100,
    2
  ) AS TURNOVER_RATE_PCT
FROM EXIT_RECORDS ER
JOIN EMPLOYEES E
  ON ER.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON E.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.EFFECTIVE_DATE <= ER.TERMINATION_DATE
  AND (EA.END_DATE IS NULL OR EA.END_DATE >= ER.TERMINATION_DATE)
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
CROSS JOIN (
  SELECT AVG(HC) AS AVG_HC FROM (
    SELECT COUNT(DISTINCT EMPLOYEE_ID) AS HC
    FROM EMPLOYEES
    WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave')
  )
)
WHERE ER.TERMINATION_DATE >= DATE_TRUNC('year', CURRENT_DATE)
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY TURNOVER_RATE_PCT DESC;

-- =========================================================================
-- DASHBOARD 3: COMPENSATION ANALYTICS
-- =========================================================================

-- 3.1: Average Base Salary by Job Grade
SELECT
  JG.GRADE_CODE,
  JG.GRADE_NAME,
  COUNT(DISTINCT C.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
  ROUND(AVG(C.AMOUNT), 2) AS AVG_BASE_SALARY,
  ROUND(MIN(C.AMOUNT), 2) AS MIN_SALARY,
  ROUND(MAX(C.AMOUNT), 2) AS MAX_SALARY,
  JG.PAY_RANGE_MIN,
  JG.PAY_RANGE_MID,
  JG.PAY_RANGE_MAX
FROM COMPENSATION_RECORDS C
JOIN EMPLOYEES E
  ON C.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON C.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN JOB_GRADES JG
  ON EA.JOB_GRADE_ID = JG.JOB_GRADE_ID
WHERE C.END_DATE IS NULL
  AND C.COMP_TYPE = 'Base'
  AND E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
GROUP BY JG.JOB_GRADE_ID, JG.GRADE_CODE, JG.GRADE_NAME, JG.PAY_RANGE_MIN, JG.PAY_RANGE_MID, JG.PAY_RANGE_MAX
ORDER BY JG.GRADE_CODE;

-- 3.2: Total Compensation Cost Summary
SELECT
  COUNT(DISTINCT C.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
  SUM(C.AMOUNT) AS TOTAL_COMPENSATION,
  ROUND(SUM(C.AMOUNT) / COUNT(DISTINCT C.EMPLOYEE_ID), 2) AS AVG_TOTAL_COMP,
  ROUND(
    SUM(CASE WHEN COMP_TYPE = 'Base' THEN AMOUNT ELSE 0 END) /
    COUNT(DISTINCT CASE WHEN COMP_TYPE = 'Base' THEN EMPLOYEE_ID END),
    2
  ) AS AVG_BASE,
  ROUND(
    SUM(CASE WHEN COMP_TYPE = 'Bonus' THEN AMOUNT ELSE 0 END) /
    COUNT(DISTINCT CASE WHEN COMP_TYPE = 'Bonus' THEN EMPLOYEE_ID END),
    2
  ) AS AVG_BONUS
FROM COMPENSATION_RECORDS C
WHERE C.END_DATE IS NULL;

-- 3.3: Compa-Ratio Distribution by Grade
SELECT
  JG.GRADE_CODE,
  JG.GRADE_NAME,
  ROUND(
    (C.AMOUNT / JG.PAY_RANGE_MID) * 100,
    1
  ) AS COMPA_RATIO,
  COUNT(*) AS EMPLOYEE_COUNT
FROM COMPENSATION_RECORDS C
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON C.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN JOB_GRADES JG
  ON EA.JOB_GRADE_ID = JG.JOB_GRADE_ID
WHERE C.END_DATE IS NULL
  AND C.COMP_TYPE = 'Base'
GROUP BY JG.JOB_GRADE_ID, JG.GRADE_CODE, JG.GRADE_NAME, C.AMOUNT, JG.PAY_RANGE_MID
ORDER BY JG.GRADE_CODE, COMPA_RATIO;

-- =========================================================================
-- DASHBOARD 4: PAY EQUITY ANALYSIS
-- =========================================================================

-- 4.1: Gender Pay Gap by Job Grade
SELECT
  JG.GRADE_CODE,
  JG.GRADE_NAME,
  ROUND(AVG(CASE WHEN E.GENDER = 'M' THEN C.AMOUNT END), 2) AS AVG_MALE_SALARY,
  ROUND(AVG(CASE WHEN E.GENDER = 'F' THEN C.AMOUNT END), 2) AS AVG_FEMALE_SALARY,
  COUNT(DISTINCT CASE WHEN E.GENDER = 'M' THEN C.EMPLOYEE_ID END) AS MALE_COUNT,
  COUNT(DISTINCT CASE WHEN E.GENDER = 'F' THEN C.EMPLOYEE_ID END) AS FEMALE_COUNT,
  ROUND(
    ((AVG(CASE WHEN E.GENDER = 'M' THEN C.AMOUNT END) -
      AVG(CASE WHEN E.GENDER = 'F' THEN C.AMOUNT END)) /
     AVG(CASE WHEN E.GENDER = 'F' THEN C.AMOUNT END)) * 100,
    2
  ) AS PAY_GAP_PCT
FROM COMPENSATION_RECORDS C
JOIN EMPLOYEES E
  ON C.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON C.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN JOB_GRADES JG
  ON EA.JOB_GRADE_ID = JG.JOB_GRADE_ID
WHERE C.END_DATE IS NULL
  AND C.COMP_TYPE = 'Base'
  AND E.GENDER IN ('M', 'F')
  AND E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
GROUP BY JG.JOB_GRADE_ID, JG.GRADE_CODE, JG.GRADE_NAME
ORDER BY JG.GRADE_CODE;

-- 4.2: Diversity Index by Ethnicity
SELECT
  ETHNICITY,
  COUNT(DISTINCT EMPLOYEE_ID) AS EMPLOYEE_COUNT,
  ROUND(
    (COUNT(DISTINCT EMPLOYEE_ID) / SUM(COUNT(DISTINCT EMPLOYEE_ID)) OVER()) * 100,
    2
  ) AS PERCENTAGE
FROM EMPLOYEES
WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave')
GROUP BY ETHNICITY
ORDER BY EMPLOYEE_COUNT DESC;

-- =========================================================================
-- DASHBOARD 5: PERFORMANCE MANAGEMENT
-- =========================================================================

-- 5.1: Performance Rating Distribution (Current Cycle)
SELECT
  RATING_LABEL,
  COUNT(DISTINCT REVIEW_ID) AS REVIEW_COUNT,
  COUNT(DISTINCT EMPLOYEE_ID) AS EMPLOYEE_COUNT,
  ROUND(
    (COUNT(DISTINCT EMPLOYEE_ID) / SUM(COUNT(DISTINCT EMPLOYEE_ID)) OVER()) * 100,
    2
  ) AS PERCENTAGE
FROM PERFORMANCE_REVIEWS
WHERE IS_FINAL_CALIBRATED = TRUE
  AND CYCLE_ID IN (
    SELECT CYCLE_ID FROM PERFORMANCE_CYCLES
    WHERE END_DATE >= DATE_TRUNC('year', CURRENT_DATE)
  )
GROUP BY RATING_LABEL
ORDER BY CASE RATING_LABEL
  WHEN 'Exceeds' THEN 1
  WHEN 'Meets' THEN 2
  WHEN 'Below' THEN 3
  ELSE 4
END;

-- 5.2: Average Goal Attainment by Department
SELECT
  D.DEPARTMENT_NAME,
  ROUND(AVG(G.ATTAINMENT_PCT), 2) AS AVG_GOAL_ATTAINMENT_PCT,
  COUNT(DISTINCT G.GOAL_ID) AS GOAL_COUNT,
  COUNT(DISTINCT G.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM GOALS G
JOIN EMPLOYEES E
  ON G.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON E.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE G.CYCLE_ID IN (
  SELECT CYCLE_ID FROM PERFORMANCE_CYCLES
  WHERE END_DATE >= DATE_TRUNC('year', CURRENT_DATE)
)
  AND E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY AVG_GOAL_ATTAINMENT_PCT DESC;

-- 5.3: Average Performance Rating by Department
SELECT
  D.DEPARTMENT_NAME,
  ROUND(AVG(PR.OVERALL_RATING), 2) AS AVG_RATING,
  COUNT(DISTINCT PR.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
  COUNT(DISTINCT PR.REVIEW_ID) AS REVIEW_COUNT
FROM PERFORMANCE_REVIEWS PR
JOIN EMPLOYEES E
  ON PR.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON E.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE PR.IS_FINAL_CALIBRATED = TRUE
  AND PR.CYCLE_ID IN (
    SELECT CYCLE_ID FROM PERFORMANCE_CYCLES
    WHERE END_DATE >= DATE_TRUNC('year', CURRENT_DATE)
  )
  AND E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY AVG_RATING DESC;

-- =========================================================================
-- DASHBOARD 6: RETENTION ANALYTICS
-- =========================================================================

-- 6.1: Voluntary Turnover Rate by Department (Last 12 Months)
SELECT
  D.DEPARTMENT_NAME,
  COUNT(DISTINCT ER.EMPLOYEE_ID) AS VOLUNTARY_SEPARATIONS,
  ROUND(
    (COUNT(DISTINCT ER.EMPLOYEE_ID) / AVG_HC) * 100,
    2
  ) AS VOLUNTARY_TURNOVER_PCT
FROM EXIT_RECORDS ER
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON ER.EMPLOYEE_ID = EA.EMPLOYEE_ID
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
CROSS JOIN (
  SELECT AVG(HC) AS AVG_HC FROM (
    SELECT COUNT(DISTINCT EMPLOYEE_ID) AS HC
    FROM EMPLOYEES
    WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave')
  )
)
WHERE ER.TERMINATION_DATE >= DATE_TRUNC('year', CURRENT_DATE)
  AND ER.TERMINATION_TYPE = 'Voluntary'
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY VOLUNTARY_TURNOVER_PCT DESC;

-- 6.2: Regrettable Attrition Rate by Department
SELECT
  D.DEPARTMENT_NAME,
  COUNT(DISTINCT ER.EMPLOYEE_ID) AS REGRETTABLE_LOSSES,
  ROUND(
    (COUNT(DISTINCT ER.EMPLOYEE_ID) / AVG_HC) * 100,
    2
  ) AS REGRETTABLE_ATTRITION_PCT
FROM EXIT_RECORDS ER
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON ER.EMPLOYEE_ID = EA.EMPLOYEE_ID
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
CROSS JOIN (
  SELECT AVG(HC) AS AVG_HC FROM (
    SELECT COUNT(DISTINCT EMPLOYEE_ID) AS HC
    FROM EMPLOYEES
    WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave')
  )
)
WHERE ER.TERMINATION_DATE >= DATE_TRUNC('year', CURRENT_DATE)
  AND ER.REGRETTABLE = TRUE
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY REGRETTABLE_ATTRITION_PCT DESC;

-- 6.3: Exit Reasons Summary
SELECT
  PRIMARY_REASON,
  COUNT(DISTINCT EMPLOYEE_ID) AS EXIT_COUNT,
  ROUND(
    (COUNT(DISTINCT EMPLOYEE_ID) / SUM(COUNT(DISTINCT EMPLOYEE_ID)) OVER()) * 100,
    2
  ) AS PERCENTAGE,
  COUNT(DISTINCT CASE WHEN REGRETTABLE = TRUE THEN EMPLOYEE_ID END) AS REGRETTABLE_COUNT
FROM EXIT_RECORDS
WHERE TERMINATION_DATE >= DATE_TRUNC('year', CURRENT_DATE)
GROUP BY PRIMARY_REASON
ORDER BY EXIT_COUNT DESC;

-- =========================================================================
-- DASHBOARD 7: RECRUITMENT ANALYTICS
-- =========================================================================

-- 7.1: Time to Fill (Days to Hire)
SELECT
  P.POSITION_TITLE,
  D.DEPARTMENT_NAME,
  ROUND(
    AVG(JULIANDAY(JR.CLOSE_DATE) - JULIANDAY(JR.OPEN_DATE)),
    1
  ) AS AVG_DAYS_TO_FILL,
  COUNT(DISTINCT JR.REQUISITION_ID) AS REQUISITION_COUNT
FROM JOB_REQUISITIONS JR
JOIN POSITIONS P
  ON JR.POSITION_ID = P.POSITION_ID
JOIN DEPARTMENTS D
  ON JR.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE JR.REQUISITION_STATUS IN ('Filled', 'Closed')
  AND JR.CLOSE_DATE >= DATE_TRUNC('quarter', CURRENT_DATE)
GROUP BY P.POSITION_ID, P.POSITION_TITLE, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY AVG_DAYS_TO_FILL DESC;

-- 7.2: Offer Acceptance Rate
SELECT
  ROUND(
    (COUNT(CASE WHEN OFFER_ACCEPTED = TRUE THEN 1 END) /
     COUNT(CASE WHEN OFFER_DATE IS NOT NULL THEN 1 END)) * 100,
    2
  ) AS OFFER_ACCEPTANCE_RATE_PCT,
  COUNT(CASE WHEN OFFER_DATE IS NOT NULL THEN 1 END) AS TOTAL_OFFERS,
  COUNT(CASE WHEN OFFER_ACCEPTED = TRUE THEN 1 END) AS OFFERS_ACCEPTED
FROM APPLICATIONS
WHERE OFFER_DATE >= DATE_TRUNC('quarter', CURRENT_DATE);

-- 7.3: Applicants per Requisition by Source
SELECT
  C.SOURCE_CHANNEL,
  COUNT(DISTINCT A.REQUISITION_ID) AS REQUISITION_COUNT,
  COUNT(DISTINCT A.APPLICATION_ID) AS TOTAL_APPLICATIONS,
  ROUND(
    COUNT(DISTINCT A.APPLICATION_ID) /
    NULLIF(COUNT(DISTINCT A.REQUISITION_ID), 0),
    1
  ) AS APPLICANTS_PER_REQ
FROM APPLICATIONS A
JOIN CANDIDATES C
  ON A.CANDIDATE_ID = C.CANDIDATE_ID
WHERE A.APPLIED_DATE >= DATE_TRUNC('quarter', CURRENT_DATE)
GROUP BY C.SOURCE_CHANNEL
ORDER BY TOTAL_APPLICATIONS DESC;

-- =========================================================================
-- DASHBOARD 8: LEARNING & DEVELOPMENT
-- =========================================================================

-- 8.1: Training Completion Rate
SELECT
  ROUND(
    (COUNT(CASE WHEN STATUS = 'Completed' THEN 1 END) / COUNT(*)) * 100,
    2
  ) AS COMPLETION_RATE_PCT,
  COUNT(*) AS TOTAL_ENROLLMENTS,
  COUNT(CASE WHEN STATUS = 'Completed' THEN 1 END) AS COMPLETED,
  COUNT(CASE WHEN STATUS = 'Enrolled' THEN 1 END) AS ENROLLED,
  COUNT(CASE WHEN STATUS = 'Overdue' THEN 1 END) AS OVERDUE,
  COUNT(CASE WHEN STATUS = 'Dropped' THEN 1 END) AS DROPPED
FROM TRAINING_ENROLLMENTS
WHERE ENROLLMENT_DATE >= DATE_TRUNC('year', CURRENT_DATE);

-- 8.2: Program Enrollment and Completion by Type
SELECT
  TP.PROGRAM_TYPE,
  TP.PROGRAM_NAME,
  COUNT(DISTINCT TE.ENROLLMENT_ID) AS TOTAL_ENROLLMENTS,
  COUNT(DISTINCT CASE WHEN TE.STATUS = 'Completed' THEN TE.ENROLLMENT_ID END) AS COMPLETED,
  ROUND(
    AVG(TE.SCORE_PCT),
    2
  ) AS AVG_COMPLETION_SCORE
FROM TRAINING_ENROLLMENTS TE
JOIN TRAINING_PROGRAMS TP
  ON TE.PROGRAM_ID = TP.PROGRAM_ID
WHERE TE.ENROLLMENT_DATE >= DATE_TRUNC('year', CURRENT_DATE)
GROUP BY TP.PROGRAM_TYPE, TP.PROGRAM_ID, TP.PROGRAM_NAME
ORDER BY TOTAL_ENROLLMENTS DESC;

-- 8.3: Employee Skills Inventory
SELECT
  S.SKILL_CATEGORY,
  S.SKILL_NAME,
  COUNT(DISTINCT ES.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
  ROUND(
    (COUNT(DISTINCT CASE WHEN ES.PROFICIENCY_LEVEL = 'Expert' THEN ES.EMPLOYEE_ID END) /
     COUNT(DISTINCT ES.EMPLOYEE_ID)) * 100,
    2
  ) AS PCT_EXPERT,
  ROUND(
    (COUNT(DISTINCT CASE WHEN ES.PROFICIENCY_LEVEL = 'Advanced' THEN ES.EMPLOYEE_ID END) /
     COUNT(DISTINCT ES.EMPLOYEE_ID)) * 100,
    2
  ) AS PCT_ADVANCED
FROM EMPLOYEE_SKILLS ES
JOIN SKILLS S
  ON ES.SKILL_ID = S.SKILL_ID
JOIN EMPLOYEES E
  ON ES.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
GROUP BY S.SKILL_CATEGORY, S.SKILL_ID, S.SKILL_NAME
ORDER BY EMPLOYEE_COUNT DESC;

-- =========================================================================
-- DASHBOARD 9: EMPLOYEE ENGAGEMENT
-- =========================================================================

-- 9.1: eNPS Score (Employee Net Promoter Score)
SELECT
  ROUND(
    (COUNT(CASE WHEN RESPONSE_SCORE >= 9 THEN 1 END) -
     COUNT(CASE WHEN RESPONSE_SCORE <= 6 THEN 1 END)) /
    COUNT(*) * 100,
    1
  ) AS eNPS_SCORE,
  COUNT(*) AS TOTAL_RESPONSES,
  COUNT(CASE WHEN RESPONSE_SCORE >= 9 THEN 1 END) AS PROMOTERS,
  COUNT(CASE WHEN RESPONSE_SCORE >= 7 AND RESPONSE_SCORE <= 8 THEN 1 END) AS PASSIVES,
  COUNT(CASE WHEN RESPONSE_SCORE <= 6 THEN 1 END) AS DETRACTORS
FROM SURVEY_RESPONSES SR
JOIN SURVEY_CAMPAIGNS SC
  ON SR.CAMPAIGN_ID = SC.CAMPAIGN_ID
WHERE SC.SURVEY_TYPE = 'eNPS'
  AND SR.QUESTION_CODE = 'eNPS'
  AND SR.SUBMITTED_AT >= DATE_TRUNC('quarter', CURRENT_DATE);

-- 9.2: Engagement Score by Department
SELECT
  D.DEPARTMENT_NAME,
  ROUND(AVG(SR.RESPONSE_SCORE), 2) AS AVG_ENGAGEMENT_SCORE,
  COUNT(DISTINCT SR.EMPLOYEE_ID) AS RESPONDENT_COUNT,
  COUNT(*) AS TOTAL_RESPONSES
FROM SURVEY_RESPONSES SR
JOIN SURVEY_CAMPAIGNS SC
  ON SR.CAMPAIGN_ID = SC.CAMPAIGN_ID
JOIN EMPLOYEES E
  ON SR.EMPLOYEE_ID = E.EMPLOYEE_ID
JOIN EMPLOYEE_ASSIGNMENTS EA
  ON E.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
JOIN DEPARTMENTS D
  ON EA.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE SC.SURVEY_TYPE IN ('Engagement', 'Pulse')
  AND SR.QUESTION_CODE = 'Q_ENGAGE'
  AND SR.SUBMITTED_AT >= DATE_TRUNC('quarter', CURRENT_DATE)
  AND E.EMPLOYEE_STATUS IN ('Active', 'On Leave')
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME
ORDER BY AVG_ENGAGEMENT_SCORE DESC;

-- 9.3: Survey Response Rate
SELECT
  SC.CAMPAIGN_NAME,
  SC.SURVEY_TYPE,
  COUNT(DISTINCT SR.EMPLOYEE_ID) AS RESPONDENTS,
  (SELECT COUNT(DISTINCT EMPLOYEE_ID) FROM EMPLOYEES WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave')) AS ELIGIBLE_EMPLOYEES,
  ROUND(
    (COUNT(DISTINCT SR.EMPLOYEE_ID) /
     (SELECT COUNT(DISTINCT EMPLOYEE_ID) FROM EMPLOYEES WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave'))) * 100,
    2
  ) AS RESPONSE_RATE_PCT,
  COUNT(*) AS TOTAL_RESPONSES
FROM SURVEY_RESPONSES SR
JOIN SURVEY_CAMPAIGNS SC
  ON SR.CAMPAIGN_ID = SC.CAMPAIGN_ID
WHERE SR.SUBMITTED_AT >= DATE_TRUNC('quarter', CURRENT_DATE)
GROUP BY SC.CAMPAIGN_ID, SC.CAMPAIGN_NAME, SC.SURVEY_TYPE
ORDER BY RESPONDENTS DESC;

-- =========================================================================
-- UTILITY QUERIES
-- =========================================================================

-- U.1: Verify Current Headcount
SELECT COUNT(DISTINCT EMPLOYEE_ID) AS CURRENT_HEADCOUNT
FROM EMPLOYEES
WHERE EMPLOYEE_STATUS IN ('Active', 'On Leave');

-- U.2: Check Data Freshness (Latest Record Dates)
SELECT
  'EMPLOYEES' AS TABLE_NAME,
  MAX(HIRE_DATE) AS LATEST_DATE
FROM EMPLOYEES
UNION ALL
SELECT 'EMPLOYEE_ASSIGNMENTS', MAX(EFFECTIVE_DATE)
FROM EMPLOYEE_ASSIGNMENTS
UNION ALL
SELECT 'COMPENSATION_RECORDS', MAX(EFFECTIVE_DATE)
FROM COMPENSATION_RECORDS
UNION ALL
SELECT 'PERFORMANCE_REVIEWS', MAX(SUBMISSION_DATE)
FROM PERFORMANCE_REVIEWS
UNION ALL
SELECT 'EXIT_RECORDS', MAX(TERMINATION_DATE)
FROM EXIT_RECORDS
UNION ALL
SELECT 'SURVEY_RESPONSES', MAX(SUBMITTED_AT)
FROM SURVEY_RESPONSES
ORDER BY TABLE_NAME;

-- U.3: Find Orphaned Records (Employees Missing Assignments)
SELECT
  E.EMPLOYEE_ID,
  E.EMPLOYEE_CODE,
  E.FIRST_NAME,
  E.LAST_NAME,
  E.HIRE_DATE,
  E.EMPLOYEE_STATUS
FROM EMPLOYEES E
LEFT JOIN EMPLOYEE_ASSIGNMENTS EA
  ON E.EMPLOYEE_ID = EA.EMPLOYEE_ID
  AND EA.END_DATE IS NULL
WHERE EA.EMPLOYEE_ID IS NULL
  AND E.EMPLOYEE_STATUS IN ('Active', 'On Leave');

-- U.4: Span of Control (Direct Reports per Manager)
SELECT
  MANAGER_ID,
  COUNT(DISTINCT EMPLOYEE_ID) AS DIRECT_REPORTS
FROM EMPLOYEE_ASSIGNMENTS
WHERE END_DATE IS NULL
  AND MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID
ORDER BY DIRECT_REPORTS DESC;

-- U.5: Check for Survey Campaign Duplicates
SELECT
  CAMPAIGN_NAME,
  SURVEY_TYPE,
  COUNT(*) AS CAMPAIGN_COUNT,
  STRING_AGG(CAST(CAMPAIGN_ID AS VARCHAR), ', ') AS CAMPAIGN_IDS,
  MIN(LAUNCH_DATE) AS EARLIEST_LAUNCH,
  MAX(LAUNCH_DATE) AS LATEST_LAUNCH
FROM SURVEY_CAMPAIGNS
GROUP BY CAMPAIGN_NAME, SURVEY_TYPE
HAVING COUNT(*) > 1
ORDER BY CAMPAIGN_NAME;

-- =========================================================================
-- END OF QUERY TEMPLATES
-- =========================================================================
-- Copy and customize these queries for your dashboards
-- Remember to add filters for Department, Location, and Date Range
-- as defined in GLOBAL_FILTERS.md
-- =========================================================================

