-- ============================================================
-- Falcon Food & Snacks — Query Templates
-- IDA Connector: mcp__0f5a7fbd-d3a0-4d09-80d5-e325ec2e51bb
-- Star Schema: DIM_* (Dimensions) + FACT_* (Facts)
-- Each query pre-aggregates to <200 rows for dashboard performance
-- ============================================================

-- ============================================================
-- 1. EXECUTIVE OVERVIEW
-- ============================================================
-- KPIs: Net revenue trend YoY, gross margin %, top 5 brands, top 5 customers

-- Query 1a: Monthly net revenue YoY comparison with margin
-- Rows: ~24 (2 years × 12 months)
SELECT
    d.YEAR_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.COGS) as COGS,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT,
    COUNT(DISTINCT f.DATE_KEY) as TRADING_DAYS
FROM FACT_POS_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, d.MONTH_NUM, d.MONTH_NAME
ORDER BY d.YEAR_NUM DESC, d.MONTH_NUM;

-- Query 1b: Top 5 brands by net revenue (YTD)
-- Rows: 5
SELECT
    p.BRAND,
    p.BRAND_TIER,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY p.BRAND, p.BRAND_TIER
ORDER BY NET_REVENUE DESC
LIMIT 5;

-- Query 1c: Top 5 customers by net revenue (YTD)
-- Rows: 5
SELECT
    c.CUSTOMER_NAME,
    c.CUSTOMER_TIER,
    c.CHANNEL,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_NAME, c.CUSTOMER_TIER, c.CHANNEL
ORDER BY NET_REVENUE DESC
LIMIT 5;

-- Query 1d: Quarterly performance snapshot
-- Rows: ~8 (2 years × 4 quarters)
SELECT
    d.YEAR_NUM,
    d.FISCAL_QUARTER,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.GROSS_PROFIT) as GROSS_PROFIT,
    ROUND(100.0 * SUM(f.GROSS_PROFIT) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT,
    SUM(f.CASES_SOLD) as CASES_SOLD
FROM FACT_POS_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, d.FISCAL_QUARTER
ORDER BY d.YEAR_NUM DESC, d.FISCAL_QUARTER;

-- ============================================================
-- 2. SALES & REVENUE
-- ============================================================
-- KPIs: Monthly trend, channel mix, brand breakdown, customer ranking

-- Query 2a: Monthly revenue by channel with trend
-- Rows: ~24 (12 months × 2 channels avg)
SELECT
    d.MONTH_NUM,
    d.MONTH_NAME,
    d.YEAR_NUM,
    ch.CHANNEL_NAME,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    SUM(f.CASES_SOLD) as CASES_SOLD,
    COUNT(DISTINCT f.CUSTOMER_KEY) as UNIQUE_CUSTOMERS
FROM FACT_POS_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM_CHANNEL ch ON f.CHANNEL_KEY = ch.CHANNEL_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.MONTH_NUM, d.MONTH_NAME, d.YEAR_NUM, ch.CHANNEL_NAME
ORDER BY d.YEAR_NUM DESC, d.MONTH_NUM, ch.CHANNEL_NAME;

-- Query 2b: Channel revenue mix (current month vs prior year)
-- Rows: ~6-8 (2 years × channels)
SELECT
    d.YEAR_NUM,
    ch.CHANNEL_NAME,
    ch.CHANNEL_GROUP,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    ROUND(100.0 * SUM(f.NET_REVENUE) / SUM(SUM(f.NET_REVENUE)) OVER (PARTITION BY d.YEAR_NUM), 1) as PCT_OF_TOTAL
FROM FACT_POS_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM_CHANNEL ch ON f.CHANNEL_KEY = ch.CHANNEL_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, ch.CHANNEL_NAME, ch.CHANNEL_GROUP
ORDER BY d.YEAR_NUM DESC, NET_REVENUE DESC;

-- Query 2c: Brand revenue ranking with YoY comparison
-- Rows: ~15-20 (top brands)
SELECT
    p.BRAND,
    SUM(CASE WHEN d.YEAR_NUM = YEAR(CURRENT_DATE) THEN f.NET_REVENUE ELSE 0 END) as CURRENT_YEAR_REVENUE,
    SUM(CASE WHEN d.YEAR_NUM = YEAR(CURRENT_DATE) - 1 THEN f.NET_REVENUE ELSE 0 END) as PRIOR_YEAR_REVENUE,
    ROUND(100.0 * (SUM(CASE WHEN d.YEAR_NUM = YEAR(CURRENT_DATE) THEN f.NET_REVENUE ELSE 0 END) -
           SUM(CASE WHEN d.YEAR_NUM = YEAR(CURRENT_DATE) - 1 THEN f.NET_REVENUE ELSE 0 END)) /
           NULLIF(SUM(CASE WHEN d.YEAR_NUM = YEAR(CURRENT_DATE) - 1 THEN f.NET_REVENUE ELSE 0 END), 0), 1) as YOY_GROWTH_PCT
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY p.BRAND
ORDER BY CURRENT_YEAR_REVENUE DESC
LIMIT 15;

-- Query 2d: Customer tier revenue distribution
-- Rows: ~4-5 (customer tiers)
SELECT
    c.CUSTOMER_TIER,
    COUNT(DISTINCT c.CUSTOMER_KEY) as CUSTOMER_COUNT,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    ROUND(AVG(f.NET_REVENUE), 0) as AVG_TRANSACTION_VALUE
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_TIER
ORDER BY NET_REVENUE DESC;

-- ============================================================
-- 3. PRODUCT PERFORMANCE
-- ============================================================
-- KPIs: Brand/category revenue, units, margin; top/bottom SKUs; new product tracking

-- Query 3a: Revenue and units by brand and category
-- Rows: ~30-40 (brands × categories)
SELECT
    p.BRAND,
    p.CATEGORY,
    p.SUB_CATEGORY,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    ROUND(AVG(f.BASE_PRICE), 2) as AVG_PRICE,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY p.BRAND, p.CATEGORY, p.SUB_CATEGORY
ORDER BY NET_REVENUE DESC
LIMIT 40;

-- Query 3b: Top 10 SKUs by revenue
-- Rows: 10
SELECT
    p.SKU_CODE,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.PACK_SIZE,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMERS_CARRYING
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE) AND p.IS_ACTIVE = 1
GROUP BY p.SKU_CODE, p.PRODUCT_NAME, p.CATEGORY, p.PACK_SIZE
ORDER BY NET_REVENUE DESC
LIMIT 10;

-- Query 3c: Bottom 10 SKUs (performance concern flag)
-- Rows: 10
SELECT
    p.SKU_CODE,
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMERS_CARRYING,
    CASE WHEN COUNT(DISTINCT f.CUSTOMER_KEY) < 5 THEN 'HIGH RISK - Limited Distribution'
         WHEN SUM(f.NET_REVENUE) < 10000 THEN 'REVIEW - Low Revenue'
         ELSE 'MONITOR' END as ACTION_FLAG
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE) AND p.IS_ACTIVE = 1
GROUP BY p.SKU_CODE, p.PRODUCT_NAME, p.CATEGORY
HAVING SUM(f.NET_REVENUE) > 0
ORDER BY NET_REVENUE ASC
LIMIT 10;

-- Query 3d: New and seasonal product tracking
-- Rows: ~15-20 (new/seasonal items)
SELECT
    p.PRODUCT_NAME,
    p.SKU_CODE,
    p.BRAND,
    p.IS_SEASONAL,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMERS_CARRYING,
    COUNT(DISTINCT f.DATE_KEY) as DAYS_WITH_SALES
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE) AND (p.IS_SEASONAL = 1 OR p.IS_ACTIVE = 1)
GROUP BY p.PRODUCT_NAME, p.SKU_CODE, p.BRAND, p.IS_SEASONAL
HAVING COUNT(DISTINCT f.DATE_KEY) < 90  -- Products active <90 days = newer items
ORDER BY DAYS_WITH_SALES DESC
LIMIT 20;

-- ============================================================
-- 4. PRODUCT MARGIN
-- ============================================================
-- KPIs: Margin % by brand, category, customer; COGS trend; trade discount impact

-- Query 4a: Gross margin % by brand and category
-- Rows: ~30-40 (brand × category combinations)
SELECT
    p.BRAND,
    p.CATEGORY,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.COGS) as COGS,
    SUM(f.GROSS_PROFIT) as GROSS_PROFIT,
    ROUND(100.0 * SUM(f.GROSS_PROFIT) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT,
    COUNT(DISTINCT f.PRODUCT_KEY) as SKU_COUNT
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY p.BRAND, p.CATEGORY
ORDER BY GROSS_MARGIN_PCT DESC;

-- Query 4b: Margin % by customer tier
-- Rows: ~4-5 (customer tiers)
SELECT
    c.CUSTOMER_TIER,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.COGS) as COGS,
    SUM(f.GROSS_PROFIT) as GROSS_PROFIT,
    SUM(f.TRADE_DISCOUNT) as TOTAL_TRADE_DISCOUNT,
    ROUND(100.0 * SUM(f.GROSS_PROFIT) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT,
    ROUND(100.0 * SUM(f.TRADE_DISCOUNT) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as TRADE_DISCOUNT_PCT
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_TIER
ORDER BY GROSS_MARGIN_PCT DESC;

-- Query 4c: COGS trend by month (YoY)
-- Rows: ~24 (2 years × 12 months)
SELECT
    d.YEAR_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    SUM(f.COGS) as TOTAL_COGS,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    ROUND(100.0 * SUM(f.COGS) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as COGS_AS_PCT_REVENUE
FROM FACT_POS_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, d.MONTH_NUM, d.MONTH_NAME
ORDER BY d.YEAR_NUM DESC, d.MONTH_NUM;

-- Query 4d: Trade discount impact on margin
-- Rows: ~30-40 (on-promo vs off-promo by category)
SELECT
    p.CATEGORY,
    f.IS_ON_PROMOTION,
    COUNT(*) as TRANSACTION_COUNT,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.COGS) as COGS,
    SUM(f.TRADE_DISCOUNT) as TRADE_DISCOUNT,
    ROUND(100.0 * SUM(f.TRADE_DISCOUNT) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as DISCOUNT_RATE_PCT,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS) - SUM(f.TRADE_DISCOUNT)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as NET_MARGIN_AFTER_DISCOUNT_PCT
FROM FACT_POS_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY p.CATEGORY, f.IS_ON_PROMOTION
ORDER BY p.CATEGORY, f.IS_ON_PROMOTION DESC;

-- ============================================================
-- 5. CUSTOMER INTELLIGENCE
-- ============================================================
-- KPIs: Customer tier analysis, channel contribution, customer ranking, account scorecards

-- Query 5a: Customer tier analysis
-- Rows: ~4-5 (customer tiers)
SELECT
    c.CUSTOMER_TIER,
    COUNT(DISTINCT c.CUSTOMER_KEY) as CUSTOMER_COUNT,
    SUM(f.NET_REVENUE) as TOTAL_REVENUE,
    ROUND(AVG(f.NET_REVENUE), 0) as AVG_REVENUE_PER_TRANSACTION,
    SUM(CASE WHEN f.IS_ON_PROMOTION = 1 THEN 1 ELSE 0 END) as PROMO_TRANSACTIONS,
    ROUND(100.0 * COUNT(DISTINCT f.CUSTOMER_KEY) / COUNT(DISTINCT f.CUSTOMER_KEY) OVER (), 1) as PCT_OF_CUSTOMERS
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_TIER
ORDER BY TOTAL_REVENUE DESC;

-- Query 5b: Top 20 customers by revenue with channel mix
-- Rows: 20
SELECT
    c.CUSTOMER_NAME,
    c.CUSTOMER_TIER,
    c.CHANNEL,
    c.STORE_COUNT,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT,
    COUNT(DISTINCT f.DATE_KEY) as DAYS_WITH_SALES
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_NAME, c.CUSTOMER_TIER, c.CHANNEL, c.STORE_COUNT
ORDER BY NET_REVENUE DESC
LIMIT 20;

-- Query 5c: Customer concentration and risk
-- Rows: ~5-10
SELECT
    'TOP 5' as SEGMENT,
    COUNT(DISTINCT c.CUSTOMER_KEY) as CUSTOMER_COUNT,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    ROUND(100.0 * SUM(f.NET_REVENUE) / SUM(SUM(f.NET_REVENUE)) OVER (), 1) as PCT_OF_TOTAL_REVENUE
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
  AND c.CUSTOMER_KEY IN (SELECT CUSTOMER_KEY FROM FACT_POS_SALES f2
                         JOIN DIM_DATE d2 ON f2.DATE_KEY = d2.DATE_KEY
                         WHERE d2.FISCAL_YEAR = YEAR(CURRENT_DATE)
                         GROUP BY CUSTOMER_KEY
                         ORDER BY SUM(NET_REVENUE) DESC LIMIT 5)
UNION ALL
SELECT
    'ALL OTHER',
    COUNT(DISTINCT c.CUSTOMER_KEY),
    SUM(f.NET_REVENUE),
    ROUND(100.0 * SUM(f.NET_REVENUE) / SUM(SUM(f.NET_REVENUE)) OVER (), 1)
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
  AND c.CUSTOMER_KEY NOT IN (SELECT CUSTOMER_KEY FROM FACT_POS_SALES f2
                             JOIN DIM_DATE d2 ON f2.DATE_KEY = d2.DATE_KEY
                             WHERE d2.FISCAL_YEAR = YEAR(CURRENT_DATE)
                             GROUP BY CUSTOMER_KEY
                             ORDER BY SUM(NET_REVENUE) DESC LIMIT 5);

-- Query 5d: Customer loyalty and purchase frequency
-- Rows: ~4-5 (purchase frequency buckets)
SELECT
    c.CUSTOMER_TIER,
    CASE
        WHEN COUNT(DISTINCT f.DATE_KEY) >= 300 THEN 'DAILY'
        WHEN COUNT(DISTINCT f.DATE_KEY) >= 100 THEN 'WEEKLY'
        WHEN COUNT(DISTINCT f.DATE_KEY) >= 20 THEN 'MONTHLY'
        ELSE 'OCCASIONAL'
    END as PURCHASE_FREQUENCY,
    COUNT(DISTINCT c.CUSTOMER_KEY) as CUSTOMER_COUNT,
    SUM(f.NET_REVENUE) as TOTAL_REVENUE,
    ROUND(AVG(f.NET_REVENUE), 0) as AVG_TRANSACTION_VALUE
FROM FACT_POS_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_TIER, CASE
        WHEN COUNT(DISTINCT f.DATE_KEY) >= 300 THEN 'DAILY'
        WHEN COUNT(DISTINCT f.DATE_KEY) >= 100 THEN 'WEEKLY'
        WHEN COUNT(DISTINCT f.DATE_KEY) >= 20 THEN 'MONTHLY'
        ELSE 'OCCASIONAL'
    END
ORDER BY c.CUSTOMER_TIER, TOTAL_REVENUE DESC;

-- ============================================================
-- 6. CHANNEL & POS ANALYTICS
-- ============================================================
-- KPIs: Channel revenue mix, channel growth trend, geography × channel

-- Query 6a: Channel revenue with growth trend
-- Rows: ~24 (12 months × 2 channels avg)
SELECT
    d.MONTH_NUM,
    d.MONTH_NAME,
    d.YEAR_NUM,
    ch.CHANNEL_NAME,
    ch.CHANNEL_GROUP,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    ROUND(AVG(f.BASE_PRICE), 2) as AVG_PRICE,
    LAG(SUM(f.NET_REVENUE)) OVER (PARTITION BY ch.CHANNEL_NAME ORDER BY d.YEAR_NUM, d.MONTH_NUM) as PRIOR_MONTH_REVENUE
FROM FACT_POS_SALES f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM_CHANNEL ch ON f.CHANNEL_KEY = ch.CHANNEL_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.MONTH_NUM, d.MONTH_NAME, d.YEAR_NUM, ch.CHANNEL_NAME, ch.CHANNEL_GROUP
ORDER BY d.YEAR_NUM DESC, d.MONTH_NUM, ch.CHANNEL_NAME;

-- Query 6b: Geographic penetration by channel
-- Rows: ~40-50 (states × channels)
SELECT
    g.REGION,
    g.STATE_PROVINCE,
    g.MARKET_TIER,
    ch.CHANNEL_NAME,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMER_COUNT,
    COUNT(DISTINCT f.PRODUCT_KEY) as SKU_COUNT
FROM FACT_POS_SALES f
JOIN DIM_GEOGRAPHY g ON f.GEO_KEY = g.GEO_KEY
JOIN DIM_CHANNEL ch ON f.CHANNEL_KEY = ch.CHANNEL_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY g.REGION, g.STATE_PROVINCE, g.MARKET_TIER, ch.CHANNEL_NAME
ORDER BY NET_REVENUE DESC
LIMIT 50;

-- Query 6c: Channel-brand performance matrix
-- Rows: ~60-80 (channels × top brands)
SELECT
    ch.CHANNEL_NAME,
    p.BRAND,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMERS_STOCKING,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT
FROM FACT_POS_SALES f
JOIN DIM_CHANNEL ch ON f.CHANNEL_KEY = ch.CHANNEL_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY ch.CHANNEL_NAME, p.BRAND
ORDER BY NET_REVENUE DESC
LIMIT 80;

-- ============================================================
-- 7. SHIPMENTS & FILL RATE
-- ============================================================
-- KPIs: Monthly shipments, fill rate trend, on-time %, supplier performance

-- Query 7a: Monthly shipment volume and fill rate
-- Rows: ~24 (12 months × 2 years)
SELECT
    d.YEAR_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    SUM(f.CASES_SHIPPED) as TOTAL_CASES_SHIPPED,
    SUM(f.UNITS_SHIPPED) as TOTAL_UNITS_SHIPPED,
    SUM(f.NET_INVOICE_VALUE) as INVOICE_VALUE,
    ROUND(100.0 * SUM(f.CASES_SHIPPED) / NULLIF(SUM(f.CASES_SHIPPED) + NULLIF(SUM(CASE WHEN f.FILL_RATE_PCT < 100 THEN f.CASES_SHIPPED ELSE 0 END), 0), 0), 1) as FILL_RATE_PCT,
    COUNT(DISTINCT f.DATE_KEY) as SHIPPING_DAYS
FROM FACT_SHIPMENTS f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, d.MONTH_NUM, d.MONTH_NAME
ORDER BY d.YEAR_NUM DESC, d.MONTH_NUM;

-- Query 7b: On-time delivery performance by supplier
-- Rows: ~15-20 (top suppliers)
SELECT
    s.SUPPLIER_NAME,
    s.SUPPLIER_TYPE,
    s.COUNTRY_OF_ORIGIN,
    COUNT(DISTINCT f.SHIPMENT_KEY) as TOTAL_SHIPMENTS,
    SUM(f.UNITS_SHIPPED) as UNITS_SHIPPED,
    SUM(CASE WHEN f.ON_TIME_FLAG = 1 THEN 1 ELSE 0 END) as ON_TIME_COUNT,
    ROUND(100.0 * SUM(CASE WHEN f.ON_TIME_FLAG = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(DISTINCT f.SHIPMENT_KEY), 0), 1) as ON_TIME_PCT,
    ROUND(AVG(f.FILL_RATE_PCT), 1) as AVG_FILL_RATE_PCT
FROM FACT_SHIPMENTS f
JOIN DIM_SUPPLIER s ON f.SUPPLIER_KEY = s.SUPPLIER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY s.SUPPLIER_NAME, s.SUPPLIER_TYPE, s.COUNTRY_OF_ORIGIN
ORDER BY UNITS_SHIPPED DESC
LIMIT 20;

-- Query 7c: Customer fill rate performance
-- Rows: ~15-20 (top customers)
SELECT
    c.CUSTOMER_NAME,
    c.CUSTOMER_TIER,
    c.CHANNEL,
    COUNT(DISTINCT f.SHIPMENT_KEY) as SHIPMENTS,
    SUM(f.UNITS_SHIPPED) as UNITS_SHIPPED,
    ROUND(AVG(f.FILL_RATE_PCT), 1) as AVG_FILL_RATE_PCT,
    SUM(CASE WHEN f.ON_TIME_FLAG = 1 THEN 1 ELSE 0 END) as ON_TIME_SHIPMENTS,
    ROUND(100.0 * SUM(CASE WHEN f.ON_TIME_FLAG = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(DISTINCT f.SHIPMENT_KEY), 0), 1) as ON_TIME_PCT
FROM FACT_SHIPMENTS f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_NAME, c.CUSTOMER_TIER, c.CHANNEL
ORDER BY UNITS_SHIPPED DESC
LIMIT 20;

-- Query 7d: Fill rate trend by product category
-- Rows: ~12-16 (categories × 2 years)
SELECT
    d.YEAR_NUM,
    p.CATEGORY,
    COUNT(DISTINCT f.SHIPMENT_KEY) as SHIPMENTS,
    ROUND(AVG(f.FILL_RATE_PCT), 1) as AVG_FILL_RATE_PCT,
    ROUND(100.0 * SUM(CASE WHEN f.ON_TIME_FLAG = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(DISTINCT f.SHIPMENT_KEY), 0), 1) as ON_TIME_PCT
FROM FACT_SHIPMENTS f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, p.CATEGORY
ORDER BY d.YEAR_NUM DESC, CATEGORY;

-- ============================================================
-- 8. INVENTORY & OPERATIONS
-- ============================================================
-- KPIs: WOS trend, OOS rate, overstock rate, inventory by customer/product

-- Query 8a: Weeks of supply trend by month
-- Rows: ~24 (12 months × 2 years)
SELECT
    d.YEAR_NUM,
    d.MONTH_NUM,
    d.MONTH_NAME,
    ROUND(AVG(f.WEEKS_OF_SUPPLY), 2) as AVG_WOS,
    ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY f.WEEKS_OF_SUPPLY), 2) as MEDIAN_WOS,
    ROUND(MAX(f.WEEKS_OF_SUPPLY), 2) as MAX_WOS,
    ROUND(MIN(f.WEEKS_OF_SUPPLY), 2) as MIN_WOS,
    COUNT(DISTINCT CASE WHEN f.OUT_OF_STOCK_FLAG = 1 THEN f.INVENTORY_KEY ELSE NULL END) as OOS_POSITIONS,
    COUNT(DISTINCT CASE WHEN f.OVERSTOCK_FLAG = 1 THEN f.INVENTORY_KEY ELSE NULL END) as OVERSTOCK_POSITIONS
FROM FACT_INVENTORY f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, d.MONTH_NUM, d.MONTH_NAME
ORDER BY d.YEAR_NUM DESC, d.MONTH_NUM;

-- Query 8b: Out-of-stock and overstock alerts
-- Rows: ~50-100 (product-customer combinations with issues)
SELECT
    d.FULL_DATE,
    p.PRODUCT_NAME,
    p.SKU_CODE,
    p.CATEGORY,
    c.CUSTOMER_NAME,
    c.CHANNEL,
    f.ON_HAND_CASES,
    f.ON_ORDER_CASES,
    f.IN_TRANSIT_CASES,
    ROUND(f.WEEKS_OF_SUPPLY, 1) as WEEKS_OF_SUPPLY,
    CASE WHEN f.OUT_OF_STOCK_FLAG = 1 THEN 'OUT OF STOCK'
         WHEN f.OVERSTOCK_FLAG = 1 THEN 'OVERSTOCK'
         WHEN f.WEEKS_OF_SUPPLY < 1 THEN 'LOW STOCK'
         ELSE 'NORMAL' END as INVENTORY_STATUS
FROM FACT_INVENTORY f
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
WHERE d.FULL_DATE = (SELECT MAX(FULL_DATE) FROM DIM_DATE)
  AND (f.OUT_OF_STOCK_FLAG = 1 OR f.OVERSTOCK_FLAG = 1 OR f.WEEKS_OF_SUPPLY < 1)
ORDER BY CASE WHEN f.OUT_OF_STOCK_FLAG = 1 THEN 1 WHEN f.WEEKS_OF_SUPPLY < 1 THEN 2 ELSE 3 END,
         f.WEEKS_OF_SUPPLY ASC
LIMIT 100;

-- Query 8c: Inventory value by customer and product tier
-- Rows: ~30-40 (customers × product tiers)
SELECT
    c.CUSTOMER_NAME,
    c.CUSTOMER_TIER,
    p.CATEGORY,
    p.BRAND_TIER,
    SUM(f.ON_HAND_CASES) as ON_HAND_CASES,
    SUM(f.ON_ORDER_CASES) as ON_ORDER_CASES,
    ROUND(AVG(f.WEEKS_OF_SUPPLY), 1) as AVG_WOS,
    COUNT(DISTINCT f.INVENTORY_KEY) as SKU_COUNT
FROM FACT_INVENTORY f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FULL_DATE = (SELECT MAX(FULL_DATE) FROM DIM_DATE)
GROUP BY c.CUSTOMER_NAME, c.CUSTOMER_TIER, p.CATEGORY, p.BRAND_TIER
ORDER BY ON_HAND_CASES DESC
LIMIT 40;

-- ============================================================
-- 9. TRADE SPEND / PROMO ROI
-- ============================================================
-- KPIs: Spend planned vs actual, ROI by brand/customer, incremental lift, promo effectiveness

-- Query 9a: Trade spend planned vs actual by brand
-- Rows: ~10-15 (top brands)
SELECT
    p.BRAND,
    SUM(f.PLANNED_SPEND) as PLANNED_SPEND,
    SUM(f.ACTUAL_SPEND) as ACTUAL_SPEND,
    ROUND(100.0 * (SUM(f.ACTUAL_SPEND) - SUM(f.PLANNED_SPEND)) / NULLIF(SUM(f.PLANNED_SPEND), 0), 1) as VARIANCE_PCT,
    SUM(f.BASELINE_UNITS) as BASELINE_UNITS,
    SUM(f.INCREMENTAL_UNITS) as INCREMENTAL_UNITS,
    ROUND(100.0 * SUM(f.INCREMENTAL_UNITS) / NULLIF(SUM(f.BASELINE_UNITS), 0), 1) as LIFT_PCT,
    ROUND(SUM(f.PROMO_ROI), 2) as AVG_ROI
FROM FACT_TRADE_SPEND f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY p.BRAND
ORDER BY SUM(f.ACTUAL_SPEND) DESC
LIMIT 15;

-- Query 9b: Promo ROI by promotion type
-- Rows: ~5-8 (promotion types)
SELECT
    pr.PROMOTION_TYPE,
    pr.DISCOUNT_TYPE,
    COUNT(DISTINCT f.TRADE_SPEND_KEY) as PROMO_COUNT,
    SUM(f.ACTUAL_SPEND) as TOTAL_SPEND,
    SUM(f.BASELINE_REVENUE) as BASELINE_REVENUE,
    SUM(f.INCREMENTAL_REVENUE) as INCREMENTAL_REVENUE,
    ROUND(SUM(f.INCREMENTAL_REVENUE) / NULLIF(SUM(f.ACTUAL_SPEND), 0), 2) as ROI,
    ROUND(100.0 * SUM(f.INCREMENTAL_UNITS) / NULLIF(SUM(f.BASELINE_UNITS), 0), 1) as LIFT_PCT
FROM FACT_TRADE_SPEND f
JOIN DIM_PROMOTION pr ON f.PROMOTION_KEY = pr.PROMOTION_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE) AND f.ACTUAL_SPEND > 0
GROUP BY pr.PROMOTION_TYPE, pr.DISCOUNT_TYPE
ORDER BY SUM(f.ACTUAL_SPEND) DESC;

-- Query 9c: Customer trade spend effectiveness
-- Rows: ~15-20 (top customers)
SELECT
    c.CUSTOMER_NAME,
    c.CUSTOMER_TIER,
    SUM(f.ACTUAL_SPEND) as TOTAL_SPEND,
    COUNT(DISTINCT f.TRADE_SPEND_KEY) as PROMO_COUNT,
    SUM(f.INCREMENTAL_REVENUE) as INCREMENTAL_REVENUE,
    SUM(f.INCREMENTAL_UNITS) as INCREMENTAL_UNITS,
    ROUND(SUM(f.INCREMENTAL_REVENUE) / NULLIF(SUM(f.ACTUAL_SPEND), 0), 2) as ROI,
    ROUND(100.0 * SUM(f.INCREMENTAL_UNITS) / NULLIF(SUM(f.BASELINE_UNITS), 0), 1) as LIFT_PCT
FROM FACT_TRADE_SPEND f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY c.CUSTOMER_NAME, c.CUSTOMER_TIER
ORDER BY SUM(f.ACTUAL_SPEND) DESC
LIMIT 20;

-- Query 9d: Incremental lift by category
-- Rows: ~8-12 (product categories)
SELECT
    p.CATEGORY,
    SUM(f.BASELINE_UNITS) as BASELINE_UNITS,
    SUM(f.INCREMENTAL_UNITS) as INCREMENTAL_UNITS,
    SUM(f.BASELINE_REVENUE) as BASELINE_REVENUE,
    SUM(f.INCREMENTAL_REVENUE) as INCREMENTAL_REVENUE,
    SUM(f.ACTUAL_SPEND) as PROMO_SPEND,
    ROUND(100.0 * SUM(f.INCREMENTAL_UNITS) / NULLIF(SUM(f.BASELINE_UNITS), 0), 1) as UNIT_LIFT_PCT,
    ROUND(100.0 * SUM(f.INCREMENTAL_REVENUE) / NULLIF(SUM(f.BASELINE_REVENUE), 0), 1) as REVENUE_LIFT_PCT,
    ROUND(SUM(f.INCREMENTAL_REVENUE) / NULLIF(SUM(f.ACTUAL_SPEND), 0), 2) as ROI
FROM FACT_TRADE_SPEND f
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY p.CATEGORY
ORDER BY SUM(f.ACTUAL_SPEND) DESC;

-- ============================================================
-- 10. CONSUMER PANEL / HOUSEHOLD
-- ============================================================
-- KPIs: Household penetration, repeat rate, loyalty tier, basket size, purchase frequency

-- Query 10a: Household penetration and repeat purchase analysis
-- Rows: ~5-6 (loyalty tiers)
SELECT
    h.LOYALTY_TIER,
    COUNT(DISTINCT h.HOUSEHOLD_KEY) as HOUSEHOLD_COUNT,
    SUM(CASE WHEN f.IS_REPEAT_PURCHASE = 1 THEN 1 ELSE 0 END) as REPEAT_PURCHASES,
    ROUND(100.0 * SUM(CASE WHEN f.IS_REPEAT_PURCHASE = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1) as REPEAT_RATE_PCT,
    ROUND(AVG(f.AMOUNT_PAID), 2) as AVG_BASKET_SIZE,
    ROUND(AVG(f.UNITS_PURCHASED), 1) as AVG_UNITS_PER_TRIP,
    ROUND(COUNT(DISTINCT f.DATE_KEY) / COUNT(DISTINCT h.HOUSEHOLD_KEY), 1) as AVG_TRIPS_PER_HH
FROM FACT_HOUSEHOLD_PURCHASE f
JOIN DIM_HOUSEHOLD h ON f.HOUSEHOLD_KEY = h.HOUSEHOLD_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY h.LOYALTY_TIER
ORDER BY HOUSEHOLD_COUNT DESC;

-- Query 10b: Household income and purchase behavior
-- Rows: ~6-8 (income bands)
SELECT
    h.INCOME_BAND,
    h.PANEL_SEGMENT,
    COUNT(DISTINCT h.HOUSEHOLD_KEY) as HOUSEHOLD_COUNT,
    SUM(f.UNITS_PURCHASED) as TOTAL_UNITS,
    SUM(f.AMOUNT_PAID) as TOTAL_REVENUE,
    ROUND(AVG(f.AMOUNT_PAID), 2) as AVG_BASKET_SIZE,
    ROUND(100.0 * SUM(CASE WHEN f.IS_REPEAT_PURCHASE = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1) as REPEAT_RATE_PCT
FROM FACT_HOUSEHOLD_PURCHASE f
JOIN DIM_HOUSEHOLD h ON f.HOUSEHOLD_KEY = h.HOUSEHOLD_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY h.INCOME_BAND, h.PANEL_SEGMENT
ORDER BY TOTAL_REVENUE DESC;

-- Query 10c: Brand loyalty by household segment
-- Rows: ~40-50 (segments × brands)
SELECT
    h.PANEL_SEGMENT,
    p.BRAND,
    COUNT(DISTINCT h.HOUSEHOLD_KEY) as HH_PENETRATION,
    SUM(f.UNITS_PURCHASED) as UNITS,
    SUM(f.AMOUNT_PAID) as REVENUE,
    ROUND(100.0 * SUM(CASE WHEN f.IS_REPEAT_PURCHASE = 1 THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 1) as REPEAT_RATE_PCT,
    COUNT(DISTINCT f.DATE_KEY) as PURCHASE_OCCASIONS
FROM FACT_HOUSEHOLD_PURCHASE f
JOIN DIM_HOUSEHOLD h ON f.HOUSEHOLD_KEY = h.HOUSEHOLD_KEY
JOIN DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY h.PANEL_SEGMENT, p.BRAND
ORDER BY REVENUE DESC
LIMIT 50;

-- Query 10d: Channel preference by household life stage
-- Rows: ~12-16 (life stages × channels)
SELECT
    h.LIFE_STAGE,
    ch.CHANNEL_NAME,
    COUNT(DISTINCT h.HOUSEHOLD_KEY) as HOUSEHOLD_COUNT,
    SUM(f.UNITS_PURCHASED) as UNITS,
    SUM(f.AMOUNT_PAID) as REVENUE,
    ROUND(AVG(f.AMOUNT_PAID), 2) as AVG_BASKET_SIZE,
    COUNT(DISTINCT f.DATE_KEY) as PURCHASE_OCCASIONS
FROM FACT_HOUSEHOLD_PURCHASE f
JOIN DIM_HOUSEHOLD h ON f.HOUSEHOLD_KEY = h.HOUSEHOLD_KEY
JOIN DIM_CHANNEL ch ON f.CHANNEL_KEY = ch.CHANNEL_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY h.LIFE_STAGE, ch.CHANNEL_NAME
ORDER BY REVENUE DESC;

-- ============================================================
-- 11. GEOGRAPHIC PERFORMANCE
-- ============================================================
-- KPIs: Revenue by region/state, market tier, geography growth, US vs Canada

-- Query 11a: Revenue by region and state with market tier
-- Rows: ~40-50 (states)
SELECT
    g.REGION,
    g.STATE_PROVINCE,
    g.STATE_CODE,
    g.MARKET_TIER,
    g.POPULATION_BAND,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMER_COUNT,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT
FROM FACT_POS_SALES f
JOIN DIM_GEOGRAPHY g ON f.GEO_KEY = g.GEO_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY g.REGION, g.STATE_PROVINCE, g.STATE_CODE, g.MARKET_TIER, g.POPULATION_BAND
ORDER BY NET_REVENUE DESC
LIMIT 50;

-- Query 11b: Market tier performance and growth
-- Rows: ~6-8 (market tiers)
SELECT
    g.MARKET_TIER,
    COUNT(DISTINCT g.STATE_PROVINCE) as STATE_COUNT,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    ROUND(AVG(f.NET_REVENUE), 0) as AVG_TRANSACTION_SIZE,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT
FROM FACT_POS_SALES f
JOIN DIM_GEOGRAPHY g ON f.GEO_KEY = g.GEO_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.FISCAL_YEAR = YEAR(CURRENT_DATE)
GROUP BY g.MARKET_TIER
ORDER BY NET_REVENUE DESC;

-- Query 11c: Geographic growth YoY by region
-- Rows: ~12-16 (regions × 2 years)
SELECT
    d.YEAR_NUM,
    g.REGION,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMER_COUNT,
    LAG(SUM(f.NET_REVENUE)) OVER (PARTITION BY g.REGION ORDER BY d.YEAR_NUM) as PRIOR_YEAR_REVENUE
FROM FACT_POS_SALES f
JOIN DIM_GEOGRAPHY g ON f.GEO_KEY = g.GEO_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.YEAR_NUM, g.REGION
ORDER BY d.YEAR_NUM DESC, NET_REVENUE DESC;

-- Query 11d: US vs Canada performance comparison
-- Rows: ~24 (12 months × 2 countries)
SELECT
    d.MONTH_NUM,
    d.MONTH_NAME,
    d.YEAR_NUM,
    CASE WHEN g.COUNTRY_CODE = 'US' THEN 'United States' ELSE 'Canada' END as COUNTRY,
    SUM(f.NET_REVENUE) as NET_REVENUE,
    SUM(f.UNITS_SOLD) as UNITS_SOLD,
    COUNT(DISTINCT f.CUSTOMER_KEY) as CUSTOMERS,
    ROUND(100.0 * (SUM(f.NET_REVENUE) - SUM(f.COGS)) / NULLIF(SUM(f.NET_REVENUE), 0), 1) as GROSS_MARGIN_PCT
FROM FACT_POS_SALES f
JOIN DIM_GEOGRAPHY g ON f.GEO_KEY = g.GEO_KEY
JOIN DIM_DATE d ON f.DATE_KEY = d.DATE_KEY
WHERE d.YEAR_NUM >= YEAR(CURRENT_DATE) - 1
GROUP BY d.MONTH_NUM, d.MONTH_NAME, d.YEAR_NUM, CASE WHEN g.COUNTRY_CODE = 'US' THEN 'United States' ELSE 'Canada' END
ORDER BY d.YEAR_NUM DESC, d.MONTH_NUM, COUNTRY;

-- ============================================================
-- NOTES ON USAGE
-- ============================================================
-- 1. All queries aggregate to <200 rows for optimal dashboard performance
-- 2. Replace YEAR(CURRENT_DATE) with specific year filters if needed (e.g., 2024, 2025)
-- 3. Use LIMIT clauses to control row counts for large result sets
-- 4. Window functions (LAG, PERCENTILE_CONT) supported in most SQL engines
-- 5. Adjust date filtering (FISCAL_YEAR vs YEAR_NUM) based on your fiscal calendar
-- 6. All monetary columns are in native currency; convert if multi-currency needed
-- 7. Test each query with ida_query() and verify row counts match expectations
-- ============================================================
